# Generated by Django 6.0.3 on 2026-03-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_alter_curso_nivel_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='nivel',
            field=models.CharField(choices=[('B', 'Básico'), ('A', 'Avançado'), ('I', 'Intermediário')], default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='estudante',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='periodo',
            field=models.CharField(choices=[('V', 'Vespertino'), ('M', 'Matutino'), ('N', 'Noturno')], default='M', max_length=1),
        ),
    ]
