# Generated by Django 6.0.3 on 2026-03-20 13:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0003_alter_curso_nivel_alter_estudante_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='codigo',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='periodo',
            field=models.CharField(choices=[('V', 'Vespertino'), ('N', 'Noturno'), ('M', 'Matutino')], default='M', max_length=1),
        ),
    ]
